name: build
on:
  push:
jobs:
  debug:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'   # Ensures nested submodules also get cloned
          fetch-depth: 0            # Ensures the correct commit of submodules is available

      - name: Setup CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          options: WARNINGS_AS_ERRORS=ON

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: ./build/Debug/Tests.exe

  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          options: WARNINGS_AS_ERRORS=ON BUILD_TESTS=OFF LINK_DYNAMICALLY=OFF ENABLE_PROFILING=OFF

      - name: Build
        run: cmake --build build --config Release
